NATURES_DATA = {
    "Adamant": {"buff": "attack", "debuff": "special_attack"},
    "Bashful": {"buff": None, "debuff": None}, # Neutra
    "Bold":    {"buff": "defense", "debuff": "attack"},
    "Brave":   {"buff": "attack", "debuff": "speed"},
    "Calm":    {"buff": "special_defense", "debuff": "attack"},
    "Careful": {"buff": "special_defense", "debuff": "special_attack"},
    "Docile":  {"buff": None, "debuff": None}, 
    "Gentle":  {"buff": "special_defense", "debuff": "defense"},
    "Hardy":   {"buff": None, "debuff": None}, 
    "Hasty":   {"buff": "speed", "debuff": "defense"},
    "Impish":  {"buff": "defense", "debuff": "special_attack"},
    "Jolly":   {"buff": "speed", "debuff": "special_attack"},
    "Lax":     {"buff": "defense", "debuff": "special_defense"},
    "Lonely":  {"buff": "attack", "debuff": "defense"},
    "Mild":    {"buff": "special_attack", "debuff": "defense"},
    "Modest":  {"buff": "special_attack", "debuff": "attack"},
    "Naive":   {"buff": "speed", "debuff": "special_defense"},
    "Naughty": {"buff": "attack", "debuff": "special_defense"},
    "Quiet":   {"buff": "special_attack", "debuff": "speed"},
    "Quirky":  {"buff": None, "debuff": None}, 
    "Rash":    {"buff": "special_attack", "debuff": "special_defense"},
    "Relaxed": {"buff": "defense", "debuff": "speed"},
    "Sassy":   {"buff": "special_defense", "debuff": "speed"},
    "Serious": {"buff": None, "debuff": None}, 
    "Timid":   {"buff": "speed", "debuff": "attack"},
}